# Using several other .travis.yml files as inspiration. See for example:
# https://github.com/MOxUnit/MOxUnit
# https://github.com/scottclowe/matlab-continuous-integration/
# https://github.com/fieldtrip/fieldtrip/blob/master/.travis.yml

language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage
# command to run tests
script:
  - pytest
  - coverage run -m unittest discover

after_success:
  - bash <(curl -s https://codecov.io/bash)